const actionTypes = Object.freeze({
    // app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    // counter
    COUNTER_INCREASE_START: 'COUNTER_INCREASE_START',
    COUNTER_INCREASE_SUCCESS: 'COUNTER_INCREASE_SUCCESS',
    COUNTER_INCREASE_FAILED: 'COUNTER_INCREASE_FAILED',
    COUNTER_DECREASE_START: 'COUNTER_DECREASE_START',
    COUNTER_DECREASE_SUCCESS: 'COUNTER_DECREASE_SUCCESS',
    COUNTER_DECREASE_FAILED: 'COUNTER_DECREASE_FAILED',
    // user
    SAVE_USER_DATA_LOGIN_SUCCESS: 'SAVE_USER_DATA_LOGIN_SUCCESS',
    SAVE_USER_DATA_LOGIN_FAILED: 'SAVE_USER_DATA_LOGIN_FAILED',
    RESET_USER_INFO_SUCCESS: 'RESET_USER_INFO_SUCCESS',
    RESET_USER_INFO_FAILED: 'RESET_USER_INFO_FAILED'
})

export default actionTypes;